# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('login_logout', '0007_auto_20160814_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changepassworduser',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='activationuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 13, 51, 53, 690214, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ChangePasswordUser',
        ),
    ]
