# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0008_auto_20160814_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='email_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activationuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 14, 20, 6, 31, 981062, tzinfo=utc)),
        ),
    ]
