# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0009_auto_20160814_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 0, 3, 34, 461003)),
        ),
    ]
