# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0010_auto_20161105_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 5, 21, 48, 13, 296407)),
        ),
    ]
