# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 23:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_logout', '0013_auto_20170824_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='new_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activationuser',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 27, 23, 23, 15, 156684)),
        ),
    ]
