# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название товара')),
                ('createDate', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
            options={
                'ordering': ['createDate'],
                'verbose_name_plural': 'Товары',
                'verbose_name': 'Товар',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['createDate'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Необязательное поле', null=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='relative',
            field=models.ForeignKey(blank=True, help_text='Необязательное поле', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория'),
        ),
    ]
