# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160710_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='complited',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
