# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_good_complited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
